Basic Data Types
==============

Numerical and Logical Types
---

In [1]:
X=5 #Set X to integer object equal to 5
print "1: X=",X

X=5.0 #Set X to float object equal to 5.0
print "2: X=",X

X=True #Set X to boolean True
print "3: X=",X

X=50000000000000000000L #Set X to long integer object equal to 5
print "4: X=",X

1: X= 5
2: X= 5.0
3: X= True
4: X= 50000000000000000000


Strings
--

In [3]:
X="This is a string" #Set X to a string object defined using double quotes
print "X=",X

 X= This is a string


In [4]:
Y='So is this!' #Set X to a string object defined using single quotes
print "Y=",Y

Y= So is this!


In [5]:
print "X[0]=",X[0] 


X[0]= T


In [27]:
print "X[0:3]=",X[0:4] # ARRAY ACCESS OMITS THE LAST ONE --> 0,1,2,3

X[0:3]= This


In [7]:
print "X.split()=", X.split()

X.split()= ['This', 'is', 'a', 'string']


In [30]:
print "X+'. '+Y=",X+ '.' + Y #USUAL PRINT ADDS A SPACE AT THE END. WITH + YOU COULD CURB IT. 
print "X+'. '+Y=",X,".",Y
print  "abc",X+'. '+ Y

X+'. '+Y= This is a string.So is this!
X+'. '+Y= This is a string . So is this!
abc This is a string. So is this!


Containers
========

Tuples
--

In [31]:
X = (1,2,3,4,5)            #Define tuple -- PARENTHESIS
print "type(X)=",type(X)

type(X)= <type 'tuple'>


In [32]:
print "X=", X           #Print the tuple 

X= (1, 2, 3, 4, 5)


In [33]:
print "X[0]=", X[0]     #Print the first element of the tuple

X[0]= 1


In [34]:
print "X[4]=", X[4]     #Print the last element of the tuple
print "X[-1]=", X[-1]   #Print the last element of the tuple-- need not have to know the index for last

X[4]= 5
X[-1]= 5


In [35]:
print "len(X)=", len(X) #Pring length of tuple

len(X)= 5


In [36]:
X[0]=5                  #Set element of tuple -- mutability -NO u cannot change elements in a tuple
print X

TypeError: 'tuple' object does not support item assignment

Lists
--

In [37]:
X = [1,2,3,4,5]            #Define list SQAURE BRACKETS
print "type(X)=",type(X)   #Show type of X

type(X)= <type 'list'>


In [38]:
print "X=", X           #Print the list

X= [1, 2, 3, 4, 5]


In [39]:
print "X[0]=", X[0]     #Print the first element of the list

X[0]= 1


In [47]:
print "X[4]=", X[4]     #Print the last element of the list
print "X[-1]=", X[-1]     #Print the last element of the list
print X[0:5]
X[4]

X[4]= 5
X[-1]= 5
[5, 2, 3, 4, 5]


5

In [42]:
print "len(X)=", len(X) #Pring length of list

len(X)= 5


In [45]:
X[0]=5                  #Change the list. 
print "X=", X           #Print the list again 

X= [5, 2, 3, 4, 5]


5

In [48]:
X.append(6)
print 'X=',X

X= [5, 2, 3, 4, 5, 6]


In [49]:
Y=X+[7,8] #append
print 'Y=',Y

Y= [5, 2, 3, 4, 5, 6, 7, 8]


In [52]:
Y=X*2 # doubles the array
print 'Y=',Y

Y= [5, 2, 3, 4, 5, 6, 5, 2, 3, 4, 5, 6]


Dictionaries
--

In [53]:
X = {"Bob": 192731, "Mary": 281927, "Joe": 103124} #Define a dictionary of key-value pairs
print "type(X)",type(X)

type(X) <type 'dict'>


In [54]:
print "X=", X                    #Print the dictionary

X= {'Bob': 192731, 'Mary': 281927, 'Joe': 103124}


In [55]:
print 'X["Joe"]=', X["Joe"]      #Print the value for Joe

X["Joe"]= 103124


In [56]:
print 'len(X)', len(X)           #Print the number of items

len(X) 3


In [57]:
print 'X.keys()=',X.keys()       #Print the list of keys

X.keys()= ['Bob', 'Mary', 'Joe']


In [58]:
print 'X.values()=',X.values()   #Print the list of values


X.values()= [192731, 281927, 103124]


In [59]:
X["Joe"]=772345                   #Change an element
print "X=", X 

X= {'Bob': 192731, 'Mary': 281927, 'Joe': 772345}


In [60]:
X["Alice"]=111111                 #Add a new element
print "X=", X 

X= {'Bob': 192731, 'Mary': 281927, 'Alice': 111111, 'Joe': 772345}


Containers with Nesting and Mixed Elements
--

In [65]:
X = [1,"Foo",False,[1,2,3],(1,True)] #Lists can contain mixed types!
print "X=", X                        #Print the list
print type(X[3])
type(X[4])

X= [1, 'Foo', False, [1, 2, 3], (1, True)]
<type 'list'>


tuple

In [67]:
#How can we get the second item in the tuple at the end of the list?
a = X[4]
a[1]

True

Assignment Dynamics
==

In [68]:
A = 5  #Assign the object "5" to the name A
B = A  #Assign the object that A referes to to the name B -- A n B refer to the same memory location.. 
#change to any will be reflected in other
print "A=",A,"B=",B 

A= 5 B= 5


In [69]:
B = 7               
print "A=",A,"B=",B 

A= 5 B= 7


In [70]:
A = [1,2,3,4,5]
B = A
print "A=",A,"B=",B 

A= [1, 2, 3, 4, 5] B= [1, 2, 3, 4, 5]


In [71]:
A = [1,2,3,4,5]
B = A
B = [5,4,3,2,1]        
print "A=",A,"B=",B  

A= [1, 2, 3, 4, 5] B= [5, 4, 3, 2, 1]


In [73]:
A = [1,2,3,4,5]
B=A
A.append(6)
B.append(7)
print "A=",A,"B=",B 

A= [1, 2, 3, 4, 5, 6, 7] B= [1, 2, 3, 4, 5, 6, 7]


In [74]:
A = [1,2,3,4,5]
B = A
B[0]=-1
print "A=",A,"B=",B

A= [-1, 2, 3, 4, 5] B= [-1, 2, 3, 4, 5]


Basic Control Flow
==


If-Elif-Else
--

In [75]:
#Basic If-Elif-Else
X=5
if(X<0):
    print("X is negative")
elif(X==0):
    print("X is zero")
else:
    print("X is positive")


X is positive


For and While
--

In [95]:
#Basic for loop using range()

for i in range(10): 
    print(i),
    
    print i # still part of for loop --indentation
    
print a;


0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
[0, 1, 2]


In [ ]:
#Basic while loop
x=5    
while(x > 0):
    print(x),
    x-=1

Mathematical and Logical Operators
==

In [96]:
print "2**4=", 2**4   #Computing Powers

2**4= 16


In [97]:
print "2/4=", 2/4     #Division of int by int

2/4= 0


In [98]:
print "2/4.=", 2/4.   #Division of int by float with .

2/4.= 0.5


In [99]:
print "2./4=", 2./4   #Division of float by int

2./4= 0.5


In [103]:
print "True or False=", True or False #Logical or

True or False= True


In [102]:
print "True and False=", True and False #Logical and

True and False= False


In [104]:
print "not(False)=", not(False) #Logical not

not(False)= True


Functions
==

In [105]:
def f(a):             #Define a basic function of 1-argument
    return a**2

print "f(2)=",f(2)


f(2)= 4


In [110]:
def g(h,a,b):         #Define a function of 3-arguments where h is a function and a and b are numbers
    return h(a)+h(b)

print "g(f,2,3)=",g(f,2,3)


g(f,2,3)= 13


NumPy Arrays
--

In [112]:
import numpy as np
X = np.array([[1,2],[3,4],[5,6]])
print type(X)
print "X=\n",X

<type 'numpy.ndarray'>
X=
[[1 2]
 [3 4]
 [5 6]]


In [113]:
print "X.shape=", X.shape

X.shape= (3, 2)


In [114]:
print "X[0,:]=", X[0,:]

X[0,:]= [1 2]


In [115]:
print "X[:,1]=", X[:,1]

X[:,1]= [2 4 6]


In [116]:
print "2*X=\n", 2*X

2*X=
[[ 2  4]
 [ 6  8]
 [10 12]]


In [117]:
print "3: 5+X=\n", 5+X


3: 5+X=
[[ 6  7]
 [ 8  9]
 [10 11]]


In [118]:
Y = np.array([[-1,1,-1]])
print "Y=\n",Y

Y=
[[-1  1 -1]]


In [119]:
print "6: Y.T=\n", Y.T

6: Y.T=
[[-1]
 [ 1]
 [-1]]


In [120]:
print "Y.dot(X)=\n", Y.dot(X)

Y.dot(X)=
[[-3 -4]]


In [121]:
print "Y.T + X =\n", Y.T + X

Y.T + X =
[[0 1]
 [4 5]
 [4 5]]


In [2]:
?